### ISSUE TITLE
Undefined variable in on /rentals/processing

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#125]
Short error:
```Ruby
undefined local variable or method `rentals' for #<#<Class:0x007fc7f3d1b3f8>:0x007fc7f56e3588>
Did you mean?  @rentals
```

Full trace:
```Ruby
Started GET "/rentals/processing" for ::1 at 2016-07-29 10:27:17 -0400
Processing by RentalsController#processing as HTML
  User Load (0.3ms)  SELECT  `users`.* FROM `users`  ORDER BY `users`.`id` ASC LIMIT 1
   (0.4ms)  SELECT DISTINCT COUNT(DISTINCT `permissions`.`id`) FROM `permissions` INNER JOIN `groups_permissions` ON `permissions`.`id` = `groups_permissions`.`permission_id` INNER JOIN `groups` ON `groups_permissions`.`group_id` = `groups`.`id` INNER JOIN `groups_users` ON `groups`.`id` = `groups_users`.`group_id` WHERE `groups_users`.`user_id` = 1 AND `permissions`.`controller` = 'rentals' AND `permissions`.`action` = 'processing'
  Permission Load (0.5ms)  SELECT DISTINCT `permissions`.* FROM `permissions` INNER JOIN `groups_permissions` ON `permissions`.`id` = `groups_permissions`.`permission_id` INNER JOIN `groups` ON `groups_permissions`.`group_id` = `groups`.`id` INNER JOIN `groups_users` ON `groups`.`id` = `groups_users`.`group_id` WHERE `groups_users`.`user_id` = 1 AND `permissions`.`controller` = 'rentals' AND `permissions`.`action` = 'processing' AND `permissions`.`id_field` IS NULL
  CACHE (0.0ms)  SELECT  `users`.* FROM `users`  ORDER BY `users`.`id` ASC LIMIT 1
  CACHE (0.0ms)  SELECT  `users`.* FROM `users`  ORDER BY `users`.`id` ASC LIMIT 1
  ItemType Load (0.3ms)  SELECT `item_types`.* FROM `item_types`  ORDER BY `item_types`.`name` ASC
  User Load (0.3ms)  SELECT `users`.* FROM `users`  ORDER BY `users`.`first_name` ASC
  CACHE (0.0ms)  SELECT `item_types`.* FROM `item_types`  ORDER BY `item_types`.`name` ASC
  Item Load (0.3ms)  SELECT `items`.* FROM `items` WHERE `items`.`deleted_at` IS NULL
  User Load (0.2ms)  SELECT `users`.* FROM `users`
  Rental Load (0.3ms)  SELECT  DISTINCT `rentals`.* FROM `rentals` WHERE (start_time >= '2016-07-29 04:00:00.000000' AND start_time <= '2016-07-30 03:59:59.999999') LIMIT 30 OFFSET 0
  Rendered rentals/_table.html.erb (43.4ms)
  Rendered rentals/processing.html.erb within layouts/application (49.2ms)
Completed 500 Internal Server Error in 61ms (ActiveRecord: 2.6ms)

NameError - undefined local variable or method `rentals' for #<#<Class:0x007fc7f3d1b3f8>:0x007fc7f56e3588>
Did you mean?  @rentals:
  app/views/rentals/_table.html.erb:12:in `_app_views_rentals__table_html_erb___4284579993449595738_70248456397640'
  actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:21:in `render'
  actionview (4.2.5.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
  app/views/rentals/processing.html.erb:20:in `_app_views_rentals_processing_html_erb___3779295739419082811_70248396427240'
  actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.5.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/logan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.3.0) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/logan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/logan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/logan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'



Started POST "/__better_errors/9d60cf15ac67dc75/variables" for ::1 at 2016-07-29 10:27:17 -0400
```

**Comment by cmednieks** [comment]
Added a fix to this in #121 , but am not sure of the purpose of this /rentals/processing view. It seems to have just existed as another list of rentals with the same function as the rentals index.

**Comment by phantompatrol** [comment]
Likely. Though, it was still a bug. Another given that no one was using it, pruning the view and controller would have also been an appropriate fix. Not judging your fix in the least, just saying that there were two equally valid ways of dealing with this issue.

**Comment by phantompatrol** [comment]
Side note, to make your life easier, you can just push one PR per issue. It is so much cleaner and means that if one of your PR is held up, you can still make progress elsewhere.
