### ISSUE TITLE
Invalid migration

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#133]
There is an issue with the most recent migration:

```Ruby
1x-vl912-128-119-15-178:probable-engine logan$ bundle exec rake db:migrate
== 20160801150013 AddValidationsToFinancialTransactions: migrating ============
-- change_column(:financial_transactions, :amount, :integer, {:null=>false, :default=>0})
   -> 0.0500s
-- change_column(:financial_transactions, :adjustment, :integer, {:null=>false, :default=>0})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Invalid use of NULL value: ALTER TABLE `financial_transactions` CHANGE `adjustment` `adjustment` int(11) DEFAULT 0 NOT NULL/Users/logan/projects/probable-engine/db/migrate/20160801150013_add_validations_to_financial_transactions.rb:4:in `change'
/Users/logan/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/logan/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Invalid use of NULL value: ALTER TABLE `financial_transactions` CHANGE `adjustment` `adjustment` int(11) DEFAULT 0 NOT NULL
/Users/logan/projects/probable-engine/db/migrate/20160801150013_add_validations_to_financial_transactions.rb:4:in `change'
/Users/logan/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/logan/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Mysql2::Error: Invalid use of NULL value
/Users/logan/projects/probable-engine/db/migrate/20160801150013_add_validations_to_financial_transactions.rb:4:in `change'
/Users/logan/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/logan/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

The issue is that the migration works when there is no data in the database, but not if there are existing records. While is not a fundamental issue (because we have not gone to production), it is worth knowing how to deal with it effectively.

**Comment by phantompatrol** [comment]
Let's see how we could have made this work. Even if it us just taking time today, CR style and walk through it!
